##################
#   Spring Settings
##################
spring:
  profiles:
    active:
      - '@spring.profiles.active@'

  liquibase:
    enabled: true

  
--- ################### stage ################### 
spring:
  config:
    activate:
      on-profile: stage
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        type: info
    show-sql: false
  liquibase:
    enabled: true

--- ################### prod ################### 
spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    enabled: true
    
--- ################### h2 ###################
 
##################
#   Spring Settings
##################
spring:
  config:
    activate:
      on-profile: h2        
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:meteo-ow;MODE=MySQL
    username: ${METEO_USER}
    password: ${METEO_PASSWD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

--- ################### mysql ################### 

##################
#   Spring Settings
##################
spring:
  config:
    activate:
      on-profile: mysql      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-host:3306/meteo-ow?&serverTimezone=Europe/Moscow&useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: ${METEO_USER}
    password: ${METEO_PASSWD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect        
